log_level: debug
pillar_merge_lists: True
auto_accept: True
pillar_safe_render_error: False

fileserver_backend:
  - roots
  - git

file_roots:
  base:
    - ${PROJECT_SALT_GIT_REPO_PATH}/salt/states
    - ${PROJECT_SALT_GIT_REPO_PATH}/salt/templates

gitfs_provider: pygit2
gitfs_privkey: ${PROJECT_HOME}/.ssh/id_rsa
gitfs_pubkey: ${PROJECT_HOME}/.ssh/id_rsa.pub
gitfs_remotes:
  - https://github.com/sensidev/node-formula
  - https://github.com/sensidev/redis-formula
  - https://github.com/sensidev/postgres-formula
  - https://github.com/sensidev/docker-formula.git
  - https://github.com/sensidev/salt-formula-java.git

pillar_roots:
  base:
    - ${PROJECT_SALT_GIT_REPO_PATH}/salt/pillar