log_level: info
pillar_merge_lists: True
top_file_merging_strategy: same

fileserver_backend:
  - git

git_pillar_update_interval: 1800

gitfs_provider: pygit2
gitfs_privkey: ${PROJECT_HOME}/.ssh/id_rsa
gitfs_pubkey: ${PROJECT_HOME}/.ssh/id_rsa.pub
gitfs_update_interval: 1800

gitfs_saltenv:
  - staging:
      - ref: ${PROJECT_SALT_GIT_DEV_BRANCH}
  - prod:
      - ref: ${PROJECT_SALT_GIT_PROD_BRANCH}

gitfs_remotes:
  - https://github.com/sensidev/node-formula:
      - all_saltenvs: master
  - https://github.com/sensidev/redis-formula:
      - all_saltenvs: master
  - https://github.com/sensidev/postgres-formula:
      - all_saltenvs: master
  - https://github.com/sensidev/docker-formula.git:
      - all_saltenvs: master
  - https://github.com/sensidev/salt-formula-java.git:
      - all_saltenvs: master

  - ${PROJECT_SALT_GIT_REPO}:
      - name: states
      - root: salt/states

  - ${PROJECT_SALT_GIT_REPO}:
      - name: templates
      - root: salt/templates

ext_pillar:
  - git:
      - ${PROJECT_SALT_GIT_DEV_BRANCH} ${PROJECT_SALT_GIT_REPO}:
          - name: devops-staging
          - root: salt/pillar
          - privkey: ${PROJECT_HOME}/.ssh/id_rsa
          - pubkey: ${PROJECT_HOME}/.ssh/id_rsa.pub
          - env: staging
      - ${PROJECT_SALT_GIT_PROD_BRANCH} ${PROJECT_SALT_GIT_REPO}:
          - name: devops-prod
          - root: salt/pillar
          - privkey: ${PROJECT_HOME}/.ssh/id_rsa
          - pubkey: ${PROJECT_HOME}/.ssh/id_rsa.pub
          - env: prod